version: '3.8'

services:
  node-app:
     build: ./
     ports:
      - "3000:3000"
     networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
        - monitoring
    ports:
      - "9090:9090"
networks:
  monitoring:

  